### ISSUE TITLE
Problem with web hosted pages

### ISSUE THREAD

**Issue by khusnetdinov** [learnyouanelm/learnyouanelm.github.io#21]
I found problem while I was reading documentations in web.
You have problems with rendering markup on 6 page.
Just look [here](http://take.ms/DgTk6)

**Comment by ghost** [comment]
Thanks. Yes.
The source file looks like this:
![screenshot 2016-09-30 17 51 35](https://cloud.githubusercontent.com/assets/8081877/18999640/960b7200-8736-11e6-95d2-005ad9768470.png)
I've not seen that markup before. I've checked and normal GitHub Markdown (```) does work on github.io (where the site is hosted) and gives the correct rendering.

**Comment by JoeyEremondi** [comment]
Yeah, I haven't looked at this in a while, I think there was previously an
issue that normal GH markdown didn't work with Jekyll, but they've since
updated it.
PRs are welcome, I haven't had a lot of time to edit this lately.

Alternately, it could just be how the markdown was represented in the source repository, I'm not writing the book from scratch, so there will be some conversion to do.
